export const USERS_DATA = [
		{
			id: 1,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 2,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 3,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 4,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 5,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 6,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 7,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 8,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 9,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 10,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 11,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 12,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 13,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 14,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 15,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 16,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 17,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 18,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 19,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 20,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
	]