export const USERS_DATA = [
		{
			id: 1,
			username: 'Arturo21',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 2,
			username: 'Diego7',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 3,
			username: 'Diego15',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 4,
			username: 'Lili2',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},
		{
			id: 5,
			username: 'Sergio3',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 6,
			username: 'Carol9',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 7,
			username: 'Gabriel01',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 8,
			username: 'Emilia20',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 9,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 10,
			username: 'Alvaro9',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 11,
			username: 'Gian3',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 12,
			username: 'Jose7',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 13,
			username: 'Amer8',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 14,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 15,
			username: 'Winston8',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 16,
			username: 'Jd4',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 17,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 18,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 19,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
		{
			id: 20,
			username: 'Carls13',
			email: 'charlesshb98@gmail.com',
			role: 'Cliente',
		},	
	]